server:
  #????HTTP??
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  security:
    user:
      name: test
      password: 123456
      roles: admin,user

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml